#!/bin/bash

if [ $(whoami) != 'root' ]; then
	echo "You must be root to run this script."
   exit 1
fi

EDID_FILE=$1
CONNECTION=$2

# Get ChimeraOS Build Release
CHIMERAOS_VERSIONID=`grep 'VERSION_ID' /etc/os-release | awk -F= '{ print $2 }' | sed s/\"//g`
CHIMERAOS_BUILDID=`grep 'BUILD_ID' /etc/os-release | awk -F= '{ print $2 }' | sed s/\"//g`
CHIMERAOS_BUILD=chimeraos-"$CHIMERAOS_VERSIONID"_"$CHIMERAOS_BUILDID"

# Inject EDID override into initramfs
replace_string "/etc/mkinitcpio.conf" "FILES=()" "FILES=(/lib/firmware/edid/${EDID_FILE})"

#  Update systemd-boot entries config
if ! grep -q "drm.edid_firmware=${CONNECTION}:edid/${EDID_FILE}"

then
    replace_string "/boot/loader/entries/frzr.conf" "iomem=relaxed" "iomem=relaxed fbcon=rotate:3 drm.edid_firmware=${CONNECTION}:edid/${EDID_FILE}"
fi

replace_string() {
mv $1 $1"+.backup" && \
    awk -v "find=$2" "replace=$3" '{
	gsub(/find/, replace);
	print;
    }' $1+".backup" > $1
}
