#!/bin/bash
if [ $(whoami) != 'root' ]; then
  echo "You must be root to run this script."
  exit 1
fi

CONNECTION=$1
EDID_FILE=$2

# Inject EDID override into initramfs
echo "Add EDID binary to mkinitcpio.conf"
cp -a /etc/mkinitcpio.conf /etc/mkinitcpio.conf.bak
sed -i 's#"FILES=()#FILES=(/lib/firmware/edid/${EDID_FILE})#' /etc/mkinitcpio.conf

#  Update systemd-boot entries config
echo "Add EDID bin firmware to boot parameters"
if ! grep -q "drm.edid_firmware=${CONNECTION}:edid/${EDID_FILE}" /boot/loader/entries/frzr.conf

then
  cp -a /boot/loader/entries/frzr.conf /boot/loader/entries/frzr.conf.bak
  sed -i "s#iomem=relaxed#iomem=relaxed drm.edid_firmware="${CONNECTION}":edid/"${EDID_FILE}"#" /boot/loader/entries/frzr.conf
fi
