#!/bin/bash

if [ $(whoami) != 'root' ]; then
  echo "You must be root to run this script."
  exit 1
fi

# Detect if the install media is running or not
if [ ! -d /tmp/frzr_root ]; then
  SUBVOL=""
  MOUNT_PATH=""
fi

IFS='.' read -ra split_arr <<< $1
echo "${split_arr[0]}"
DEPLOYMENT_DSDT_PATH="${SUBVOL}/usr/lib/firmware/dsdt/${1}"
BOOTLOADER_CONFIG="${MOUNT_PATH}/boot/loader/entries/frzr.conf"
OVERRIDE_LOG="${MOUNT_PATH}/etc/device-quirks/dsdt_override.log"
BIOS_DATE=$(cat /sys/class/dmi/id/bios_date)
BIOS_RELEASE=$(cat /sys/class/dmi/id/bios_release)
BIOS_VENDOR=$(cat /sys/class/dmi/id/bios_vendor)
BIOS_VERSION=$(cat /sys/class/dmi/id/bios_version)

# Grab previous stored values.
source $OVERRIDE_LOG

# Before doing anything we must check the checksum of the device in use against the known pool of patchable firmwares
cat /sys/firmware/acpi/tables/DSDT > system-dumped-dsdt.dat
# Dump DSDT from the system
iasl -d system-dumped-dsdt.dat
iasl -tc system-dumped-dsdt.dat

dsl_file="system-dumped-dsdt.dsl"

# Use sed to extract the checksum value from the DSL file
checksum=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "$dsl_file")
checksum2=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "$DEPLOYMENT_DSDT_PATH")

echo "Checksum value from system dump: $checksum"
echo "Checksum of shipped DSDT: $checksum2"

APPLY_PATCH=0
# Compare the checksums
if [ "$checksum" = "$checksum2" ]; then
  echo "Checksums match! We are able to patch the firmware"
  APPLY_PATCH=1
elif [ "$BIOS_DATE" == "$LAST_BIOS_DATE" ] && \
     [ "$BIOS_RELEASE" == "$LAST_BIOS_RELEASE" ] && \
     [ "$BIOS_VENDOR" == "$LAST_BIOS_VENDOR" ] && \
     [ "$BIOS_VERSION" == "$LAST_BIOS_VERSION" ] && \
     [ "$1" == "$LAST_DSDT" ]; then
  echo "ACPI Override confirmed in use. We can re-apply the override"
  APPLY_PATCH=1
else
  echo "Checksums do not match! We can't apply the patch!"
  APPLY_PATCH=0
fi
echo $APPLY_PATCH
