#!/bin/bash

if [ $(whoami) != 'root' ]; then
  echo "You must be root to run this script."
  exit 1
fi

# Detect if the install media is running or not
if [ ! -d /tmp/frzr_root ]; then
  SUBVOL=""
  MOUNT_PATH=""
fi

BIOS_DATE=$(cat /sys/class/dmi/id/bios_date)
BIOS_RELEASE=$(cat /sys/class/dmi/id/bios_release)
BIOS_VENDOR=$(cat /sys/class/dmi/id/bios_vendor)
BIOS_VERSION=$(cat /sys/class/dmi/id/bios_version)
BOOTLOADER_CONFIG="${MOUNT_PATH}/boot/loader/entries/frzr.conf"
DSDT_OVERRRIDES=$1
OVERRIDE_LOG="${MOUNT_PATH}/etc/device-quirks/dsdt_override.log"

# Grab previous stored values.
source $OVERRIDE_LOG

# Before doing anything we must check the checksum of the device in use against the known pool of patchable firmwares
cat /sys/firmware/acpi/tables/DSDT > system-dumped-dsdt.dat
iasl -d system-dumped-dsdt.dat
iasl -tc system-dumped-dsdt.dat
checksum=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "system-dumped-dsdt.dsl")

APPLY_PATCH=""
for DSDT in $DSDT_OVERRIDES; do
  DEPLOYMENT_DSDT_PATH="${SUBVOL}/usr/lib/firmware/dsdt/${DSDT}"


  # Use sed to extract the checksum value from the DSL file
  checksum2=$(sed -n 's/.*Checksum[[:space:]]\+\(0x[[:xdigit:]]\+\).*/\1/p' "$DEPLOYMENT_DSDT_PATH")
  # Compare the checksums
  if [ "$checksum" = "$checksum2" ]; then
    APPLY_PATCH=$DSDT
  elif [ "$BIOS_DATE" == "$LAST_BIOS_DATE" ] && \
       [ "$BIOS_RELEASE" == "$LAST_BIOS_RELEASE" ] && \
       [ "$BIOS_VENDOR" == "$LAST_BIOS_VENDOR" ] && \
       [ "$BIOS_VERSION" == "$LAST_BIOS_VERSION" ] && \
       [ "$DSDT" == "$LAST_DSDT" ]; then
    APPLY_PATCH=$DSDT
    break
  fi
echo $APPLY_PATCH
